name: gv_demo_action

inputs:
  REPO_NAME:
    description: "Repository name (e.g., org/project)"
    required: true
  BRANCH_NAME:
    description: "Branch name"
    required: true
  COMMIT_HASH:
    description: "Commit hash"
    required: true
  PATH_TO_CODE:
    description: "Path to root folder of C/C++ project"
    required: true
  PATH_TO_BUILDING_SCRIPT:
    description: "Relative path to build script from PATH_TO_CODE"
    required: true
  AUTH_URL:
    description: "URL to authentication service"
    required: true
  APP_URL:
    description: "URL to VVM endpoint"
    required: true
  USERNAME:
    description: "Username for authentication"
    required: true
  PASSWORD:
    description: "Password for authentication"
    required: true
  TOKEN:
    description: GitHub token with access to this repo
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout self
    uses: actions/checkout@v3
    with:
      repository: lukaszgosiewski/guidline
      token: ${{ inputs.TOKEN }}
      path: self
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.10'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install requests python-magic
    shell: pwsh

  - name: Create output directory
    run: mkdir -p output
    shell: pwsh

  - name: Run CodeQL Analysis
    run: |
      echo "Full current path:"
      pwd
      echo "All files with full paths:"
      find "$(pwd)"
      python self/wrap.py "$(realpath "${{ inputs.PATH_TO_CODE }}")" "$(realpath "${{ inputs.PATH_TO_BUILDING_SCRIPT }}")" "${{ inputs.REPO_NAME }}" "${{ inputs.BRANCH_NAME }}" "${{ inputs.COMMIT_HASH }}" "${{ inputs.AUTH_URL }}" "${{ inputs.APP_URL }}" "${{ inputs.USERNAME }}" "${{ inputs.PASSWORD }}"
    shell: pwsh
    env:
      PYTHONUNBUFFERED: 1
